name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Revisar el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Paso 3: Instalar dependencias (asegúrate de tener un requirements.txt con todas las dependencias necesarias)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Paso 4: Iniciar el servidor web Flask en segundo plano
    - name: Start Flask app in background
      run: |
        nohup python app.py &  # Reemplaza con el nombre de tu archivo o comando para iniciar el servidor
        sleep 5  # Espera 5 segundos para asegurarte de que el servidor ha arrancado correctamente
    
    # Paso 5: Ejecutar los tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Asegúrate de que los tests están en la carpeta 'tests' o ajusta el nombre de la carpeta
