name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Obtener el código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Instalar Chrome y ChromeDriver
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    # Paso 5: Verificar que Chrome y ChromeDriver están instalados
    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version || (echo "Chrome no está instalado correctamente" && exit 1)
        chromedriver --version || (echo "ChromeDriver no está instalado correctamente" && exit 1)

    # Paso 6: Iniciar la aplicación Flask
    - name: Start Flask app
      run: |
        nohup python app.py > flask.log 2>&1 &  # Cambia app.py por el nombre de tu aplicación
        sleep 10  # Esperar que Flask se inicie
        curl -f http://127.0.0.1:5000 || (echo "Flask no está en ejecución" && cat flask.log && exit 1)

    # Paso 7: Ejecutar los tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Ajusta si la carpeta de tests no es 'tests'
