name: Python CI

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama en la que estés trabajando
  pull_request:
    branches:
      - main  # Cambia 'main' por la rama en la que estés trabajando

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Aquí pones la versión de Python que estás utilizando "AH MIGO"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (CI specific step)
      run: |
        if [ "$CI" = "true" ]; then
          echo "Estam en CI, executant els tests en GitHub Actions"
          python -m unittest discover -s tests
        else
          echo "Estam en el entorn local, executant los tests localmente"
          python -m unittest discover -s tests
        fi
